/*
Deployment script for dbQuikCRM

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "dbQuikCRM"
:setvar DefaultFilePrefix "dbQuikCRM"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering SqlTable [dbo].[tbCustomers]...';


GO
ALTER TABLE [dbo].[tbCustomers] ALTER COLUMN [customerShortName] NCHAR (50) NOT NULL;


GO
PRINT N'Creating SqlUniqueConstraint [dbo].[IX_tbCustomers]...';


GO
ALTER TABLE [dbo].[tbCustomers]
    ADD CONSTRAINT [IX_tbCustomers] UNIQUE NONCLUSTERED ([customerShortName] ASC);


GO
PRINT N'Refreshing SqlView [dbo].[vCustomersForNameWithDetails]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vCustomersForNameWithDetails]';


GO
PRINT N'Refreshing SqlView [dbo].[vCustomersForShortName]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vCustomersForShortName]';


GO
PRINT N'Refreshing SqlView [dbo].[vCustomersForUnionWithPotentialCustomers]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vCustomersForUnionWithPotentialCustomers]';


GO
PRINT N'Refreshing SqlView [dbo].[vCustomersUnionWithPotentialCustomers]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vCustomersUnionWithPotentialCustomers]';


GO
PRINT N'Altering SqlScalarFunction [dbo].[fncCustShortNameForCustID]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
ALTER FUNCTION dbo.fncCustShortNameForCustID (@CustID smallint)
RETURNS nchar(50) AS  
BEGIN 
	DECLARE @CustShortName nchar(50)
	SELECT @CustShortName = CustomerShortName
	FROM tbCustomers
	WHERE CustomerID = @CustID
	RETURN (@CustShortName) 
END
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing SqlView [dbo].[vHistoryReservesOfWorkingHours]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vHistoryReservesOfWorkingHours]';


GO
PRINT N'Refreshing SqlView [dbo].[vOpenReservesOfWorkingHours]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vOpenReservesOfWorkingHours]';


GO
PRINT N'Refreshing SqlInlineTableValuedFunction [dbo].[fncCustomersWithContactAndMainAddress]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[fncCustomersWithContactAndMainAddress]';


GO
PRINT N'Refreshing SqlInlineTableValuedFunction [dbo].[fncSystemsDetails]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[fncSystemsDetails]';


GO
PRINT N'Refreshing SqlInlineTableValuedFunction [dbo].[fncSystemsDetailsForDate]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[fncSystemsDetailsForDate]';


GO
PRINT N'Refreshing SqlInlineTableValuedFunction [dbo].[fncSystemsDetailsForSearching]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[fncSystemsDetailsForSearching]';


GO
PRINT N'Refreshing SqlProcedure [dbo].[spLastMonthReferencesFromCustomersForUserName]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[spLastMonthReferencesFromCustomersForUserName]';


GO
PRINT N'Refreshing SqlProcedure [dbo].[spOpenReferencesFromCustomersForUserName]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[spOpenReferencesFromCustomersForUserName]';


GO
PRINT N'Refreshing SqlProcedure [dbo].[spCustomersTasksForPerformancePlanning]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[spCustomersTasksForPerformancePlanning]';


GO
PRINT N'Update complete.';


GO
